version: "3.4"

services:
  dns:
    container_name: beatrice-dns
    image: beatrice-dns:${VERSION}
    build:
      context: ../..
      dockerfile: ./packages/dns/Dockerfile
    command: yarn start --scope=@beatrice/dns
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT_DNS_APP: 53
      PORT_DNS_API: 80
    extra_hosts:
      - beatrice:host-gateway
    ports:
      - "2053:53/tcp"
      - "2053:53/udp"
      - "9053:80"
