version: "3.4"

services:
  revproxy:
    container_name: beatrice-revproxy
    image: beatrice-revproxy:${VERSION}
    build:
      context: ../..
      dockerfile: ./packages/revproxy/Dockerfile
    command: yarn start --scope=@beatrice/revproxy
    restart: unless-stopped
    environment:
      NODE_ENV: production
      CERT_DIR: /certs
      PORT_REVPROXY_API: 8080
      PORT_REVPROXY_HTTP: 80
      PORT_REVPROXY_HTTPS: 443
      USE_HTTP2: "false"
    extra_hosts:
      - beatrice:host-gateway
    volumes:
      - /var/www/certs:/certs
    ports:
      - "80:80"
      - "443:443"
      - "9054:8080"
