require("dotenv").config();

import app from "./app";

const { DOMAIN, NAMECHEAP_APIKEY, NAMECHEAP_USERNAME, SCHEDULE } = process.env;

if (DOMAIN && NAMECHEAP_APIKEY && NAMECHEAP_USERNAME) {
  app(DOMAIN, NAMECHEAP_APIKEY, NAMECHEAP_USERNAME, SCHEDULE);
}
