version: "3.4"

services:
  feature:
    container_name: beatrice-feature
    image: beatrice-feature:${VERSION}
    build:
      context: ../..
      dockerfile: ./packages/feature/Dockerfile
    command: yarn start --scope=@beatrice/feature
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT_FEATURE_API: 80
    extra_hosts:
      - beatrice:host-gateway
    ports:
      - "9056:80"
