# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [main]

jobs:
  beatrice-test:
    runs-on: self-hosted
    steps:
      - uses: borales/actions-yarn@v2.3.0
        name: Install dependencies
        with:
          cmd: build:install
      - uses: borales/actions-yarn@v2.3.0
        name: Run Test
        with:
          cmd: test
